const Friends =
{ users:
   [ { id: 630791420,
       id_str: '630791420',
       name: 'zach akin',
       screen_name: 'zach_akin',

       location: 'McKenzie, TN',
       description: '18 | BU Soccer',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 440,
       friends_count: 442,
       listed_count: 1,
       created_at: 'Mon Jul 09 04:46:27 +0000 2012',
       favourites_count: 4146,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 2133,
       lang: 'en',
       status: [Object],
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/916344856468951041/JqaNklOt_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/916344856468951041/JqaNklOt_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/630791420/1506535446',

       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: true,
       live_following: false,
       follow_request_sent: false,
       notifications: false,
       muting: false,
       blocking: false,
       blocked_by: false,
       translator_type: 'none' },
     { id: 3308337176,
       id_str: '3308337176',
       name: 'Swagbucks Code Alert',
       screen_name: 'swagcodesalert',
       location: '',
       description: 'I post only Swagbuck Codes the instant they appear!',
       url: 'http://t.co/rUfk5LCajj',
       entities: [Object],
       protected: false,
       followers_count: 5674,
       friends_count: 1765,

       listed_count: 13,
       created_at: 'Fri Aug 07 01:50:59 +0000 2015',
       favourites_count: 14,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 1381,
       lang: 'en',
       status: [Object],
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/633788472168284160/T1Y12qAT_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/633788472168284160/T1Y12qAT_normal.jpg',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,

       following: true,
       live_following: false,
       follow_request_sent: false,
       notifications: false,
       muting: false,
       blocking: false,
       blocked_by: false,
       translator_type: 'none' },
     { id: 137060402,
       id_str: '137060402',
       name: 'Swag Code Spoiler',
       screen_name: 'swagcodespoiler',
       location: '',
       description: 'Follow us for updates on new swag codes!\r\n\r\nWe won\'t respond to tweets. For help, please visit the chatbox at http://t.co/TmO7XLuASM',
       url: 'http://t.co/TmO7XLuASM',
       entities: [Object],
       protected: false,
       followers_count: 36600,
       friends_count: 0,
       listed_count: 105,
       created_at: 'Sun Apr 25 17:31:24 +0000 2010',
       favourites_count: 0,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,

       verified: false,
       statuses_count: 4049,
       lang: 'en',
       status: [Object],
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '022330',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/1727758195/image_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/1727758195/image_normal.jpg',
       profile_link_color: '0084B4',
       profile_sidebar_border_color: 'A8C7F7',
       profile_sidebar_fill_color: 'C0DFEC',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: false,
       live_following: false,
       follow_request_sent: false,
       notifications: false,
       muting: false,

       blocking: false,
       blocked_by: false,
       translator_type: 'none' },
     { id: 74859648,
       id_str: '74859648',
       name: 'Kurt Schmid',
       screen_name: 'kurtschmid15',
       location: 'Southern California ',
       description: 'LA Galaxy \nDirector of Player Personnel and Scouting',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 2298,
       friends_count: 1008,
       listed_count: 94,
       created_at: 'Wed Sep 16 22:42:18 +0000 2009',
       favourites_count: 8,
       utc_offset: null,
       time_zone: null,
       geo_enabled: true,
       verified: false,
       statuses_count: 1092,
       lang: 'en',
       status: [Object],
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,

       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/928771470808903680/p093ejoV_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/928771470808903680/p093ejoV_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/74859648/1510271249',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: true,
       live_following: false,
       follow_request_sent: false,
       notifications: false,
       muting: false,
       blocking: false,
       blocked_by: false,
       translator_type: 'none' },
     { id: 548714993,
       id_str: '548714993',
       name: 'LukeSellers',

       screen_name: 'lukesellers4',
       location: 'Yorkshire/Tennessee',
       description: 'instagram-luke_sellers96',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 928,
       friends_count: 604,
       listed_count: 1,
       created_at: 'Sun Apr 08 21:03:13 +0000 2012',
       favourites_count: 2317,
       utc_offset: null,
       time_zone: null,
       geo_enabled: true,
       verified: false,
       statuses_count: 8559,
       lang: 'en',
       status: [Object],
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/936801639234600960/tyOdy_nd_normal.jpg',

       profile_image_url_https: 'https://pbs.twimg.com/profile_images/936801639234600960/tyOdy_nd_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/548714993/1512185892',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: true,
       live_following: false,
       follow_request_sent: false,
       notifications: false,
       muting: false,
       blocking: false,
       blocked_by: false,
       translator_type: 'none' } ],
  next_cursor: 1581796528362869500,
  next_cursor_str: '1581796528362869518',
  previous_cursor: 0,
  previous_cursor_str: '0' }

  module.exports = Friends;
