var Tweets =
[ { created_at: 'Sun Jun 03 19:05:25 +0000 2018',
    id: 1003351971070390300,
    id_str: '1003351971070390272',
    text: 'One step at a time. #project7',
    truncated: false,
    entities: { hashtags: [Array], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',

    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 916884877244584000,
       id_str: '916884877244583937',
       name: 'Kebba Demba',
       screen_name: 'KB_demba',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 6,
       friends_count: 21,
       listed_count: 0,
       created_at: 'Sun Oct 08 04:36:04 +0000 2017',
       favourites_count: 1,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 2,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,

       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/1001866066178473984/Y0SJPDXg_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/1001866066178473984/Y0SJPDXg_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/916884877244583937/1527699327',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: true,
    retweeted: false,

    lang: 'en' },
  { created_at: 'Sun Jun 03 19:02:35 +0000 2018',
    id: 1003351258084855800,
    id_str: '1003351258084855814',
    text: 'RT @muftimenk: Remember, you don’t need people’s approval to be happy. If they have issues with you, it’s not about you, it’s about their i…',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Array], urls: [] },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 916884877244584000,
       id_str: '916884877244583937',
       name: 'Kebba Demba',
       screen_name: 'KB_demba',
       location: '',
       description: '',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 6,
       friends_count: 21,
       listed_count: 0,
       created_at: 'Sun Oct 08 04:36:04 +0000 2017',

       favourites_count: 1,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 2,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'F5F8FA',
       profile_background_image_url: null,
       profile_background_image_url_https: null,
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/1001866066178473984/Y0SJPDXg_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/1001866066178473984/Y0SJPDXg_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/916884877244583937/1527699327',
       profile_link_color: '1DA1F2',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: true,
       default_profile_image: false,
       following: false,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },

    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Fri Jun 01 23:38:25 +0000 2018',
       id: 1002695896759521300,
       id_str: '1002695896759521281',
       text: 'Remember, you don’t need people’s approval to be happy. If they have issues with you, it’s not about you, it’s abou… https://t.co/Tld1kJOyN2',
       truncated: true,
       entities: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 13245,
       favorite_count: 20176,
       favorited: false,
       retweeted: true,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 13245,
    favorite_count: 0,
    favorited: false,
    retweeted: true,
    lang: 'en' } ]

module.exports = Tweets;
